In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

2.2.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [4]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
z=np.zeros((10,10))
print('%d bytes' % (z.size*z.itemsize))


800 bytes


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
%run 'python -c "import numpy; numpy.info(numpy.add)" '

Exception: File `"'python"` not found.

In [10]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
z=np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [15]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
nz=np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


In [5]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
z=np.random.random((3, 3, 3))
print(z)

[[[7.56226651e-01 1.25903109e-01 4.24685907e-01]
  [2.83890141e-01 1.20461096e-01 3.37921913e-01]
  [1.25875783e-01 8.20480734e-01 7.69035467e-01]]

 [[1.96365160e-01 3.67232262e-01 8.61312440e-02]
  [7.90082091e-03 3.20252106e-01 8.08190514e-01]
  [4.72884351e-02 2.26955452e-01 6.66601459e-01]]

 [[6.72412990e-04 4.41987877e-01 1.42313606e-01]
  [1.41938734e-01 8.68865611e-01 2.85103552e-01]
  [9.36221206e-01 9.14338618e-01 1.11592565e-01]]]


In [11]:
z=np.random.random((10, 10))
zmin, zmax=z.min(), z.max()
print(zmax, zmin)

0.9954204134830354 0.012286070119154502


In [25]:
z=np.random.random(30)
m=z.mean()
print(m)

0.4833508421363831


In [29]:
z=np.ones((10, 10))
z[1:-1, 1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:
z=np.ones((5, 5))
z=np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False
inf


In [52]:
z=np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [55]:
z=np.zeros((8, 8), dtype=int)
z[1::2, ::2]=1
z[::2, 1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [57]:
print(np.unravel_index(100,(6, 7, 8)))

(np.int64(1), np.int64(5), np.int64(4))


In [62]:
z=np.tile(np.array([[0, 1], [0, 1]]), (4, 4))
print(z)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [63]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.50576492  1.36170749  0.28208331 -1.90813859  0.67238595]
 [-1.08692248  1.48900869 -1.31166175  1.11989887  1.52308951]
 [-0.96780123  1.04857391  0.53913473  0.00258002  0.18975663]
 [ 0.07135142  0.53273826 -0.6350895  -0.68398511 -1.57999267]
 [-0.82732775 -0.95649609  0.22733107 -0.02324697 -0.58474264]]


In [66]:
color=np.dtype([("r", np.ubyte, 1),
                ('g', np.ubyte, 1),
                ('b', np.ubyte, 1),
                ('a', np. ubyte, 1)])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


In [72]:
z=np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(z)

z=np.ones((5, 3)) @ np.ones((3, 2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [81]:
z=np.arange(11)
z[(3<z)&(z<=8)] *= -1
print(Z)

[[ 1.50576492  1.36170749  0.28208331 -1.90813859  0.67238595]
 [-1.08692248  1.48900869 -1.31166175  1.11989887  1.52308951]
 [-0.96780123  1.04857391  0.53913473  0.00258002  0.18975663]
 [ 0.07135142  0.53273826 -0.6350895  -0.68398511 -1.57999267]
 [-0.82732775 -0.95649609  0.22733107 -0.02324697 -0.58474264]]


In [82]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [85]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\User\AppData\Local\Temp\ipykernel_15032\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\User\AppData\Local\Temp\ipykernel_15032\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\User\AppData\Local\Temp\ipykernel_15032\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [86]:

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -6.  -5.   2.  -3.   3.   1.   7.  -3. -10.  -4.]


In [99]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1, Z2))

[3 5 6 8 9]
